using FluentMigrator;
using System;

namespace BitPro.SchoolMate.Migrations.DefaultDB
{
    [Migration(20200302171200)]
    public class DefaultDB_20200302_171200_DefaultDataCounties
        : AutoReversingMigration
    {
        public override void Up()
        {


            this.Insert.IntoTable("Countries").Row(new { Code = "ABW", CountryName = "Aruba", CurrencyId = 14 });
            this.Insert.IntoTable("Countries").Row(new { Code = "AFG", CountryName = "Afghanistan", CurrencyId = 3 });
            this.Insert.IntoTable("Countries").Row(new { Code = "AGO", CountryName = "Angola", CurrencyId = 8 });
            this.Insert.IntoTable("Countries").Row(new { Code = "AIA", CountryName = "Anguilla", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ALA", CountryName = "Åland Islands", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ALB", CountryName = "Albania", CurrencyId = 6 });
            this.Insert.IntoTable("Countries").Row(new { Code = "AND", CountryName = "Andorra", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ARE", CountryName = "United Arab Emirates", CurrencyId = 2 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ARG", CountryName = "Argentina", CurrencyId = 10 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ARM", CountryName = "Armenia", CurrencyId = 7 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ASM", CountryName = "American Samoa", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ATA", CountryName = "Antarctica", CurrencyId = 9 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ATF", CountryName = "French Southern Territories", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ATG", CountryName = "Antigua and Barbuda", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "AUS", CountryName = "Australia", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "AUT", CountryName = "Austria", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "AZE", CountryName = "Azerbaijan", CurrencyId = 16 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BDI", CountryName = "Burundi", CurrencyId = 24 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BEL", CountryName = "Belgium", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BEN", CountryName = "Benin", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BFA", CountryName = "Burkina Faso", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BGD", CountryName = "Bangladesh", CurrencyId = 19 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BGR", CountryName = "Bulgaria", CurrencyId = 22 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BHR", CountryName = "Bahrain", CurrencyId = 23 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BHS", CountryName = "Bahamas", CurrencyId = 31 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BIH", CountryName = "Bosnia and Herzegovina", CurrencyId = 17 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BLM", CountryName = "Saint Barthélemy", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BLR", CountryName = "Belarus", CurrencyId = 35 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BLZ", CountryName = "Belize", CurrencyId = 36 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BMU", CountryName = "Bermuda", CurrencyId = 27 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BOL", CountryName = "Bolivia (Plurinational State of)", CurrencyId = 29 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BRA", CountryName = "Brazil", CurrencyId = 30 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BRB", CountryName = "Barbados", CurrencyId = 18 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BRN", CountryName = "Brunei Darussalam", CurrencyId = 28 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BTN", CountryName = "Bhutan", CurrencyId = 32 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BVT", CountryName = "Bouvet Island", CurrencyId = 33 });
            this.Insert.IntoTable("Countries").Row(new { Code = "BWA", CountryName = "Botswana", CurrencyId = 34 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CAF", CountryName = "Central African Republic", CurrencyId = 40 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CAN", CountryName = "Canada", CurrencyId = 37 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CCK", CountryName = "Cocos (Keeling) Islands", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CHE", CountryName = "Switzerland", CurrencyId = 42 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CHL", CountryName = "Chile", CurrencyId = 45 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CHN", CountryName = "China", CurrencyId = 47 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CIV", CountryName = "Côte d'Ivoire", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CMR", CountryName = "Cameroon", CurrencyId = 40 });
            this.Insert.IntoTable("Countries").Row(new { Code = "COD", CountryName = "Congo, Democratic Republic of the", CurrencyId = 39 });
            this.Insert.IntoTable("Countries").Row(new { Code = "COG", CountryName = "Congo", CurrencyId = 40 });
            this.Insert.IntoTable("Countries").Row(new { Code = "COK", CountryName = "Cook Islands", CurrencyId = 44 });
            this.Insert.IntoTable("Countries").Row(new { Code = "COL", CountryName = "Colombia", CurrencyId = 48 });
            this.Insert.IntoTable("Countries").Row(new { Code = "COM", CountryName = "Comoros", CurrencyId = 117 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CPV", CountryName = "Cabo Verde", CurrencyId = 51 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CRI", CountryName = "Costa Rica", CurrencyId = 49 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CUB", CountryName = "Cuba", CurrencyId = 50 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CXR", CountryName = "Christmas Island", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CYM", CountryName = "Cayman Islands", CurrencyId = 122 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CYP", CountryName = "Cyprus", CurrencyId = 53 });
            this.Insert.IntoTable("Countries").Row(new { Code = "CZE", CountryName = "Czechia", CurrencyId = 54 });
            this.Insert.IntoTable("Countries").Row(new { Code = "DEU", CountryName = "Germany", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "DJI", CountryName = "Djibouti", CurrencyId = 56 });
            this.Insert.IntoTable("Countries").Row(new { Code = "DMA", CountryName = "Dominica", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "DNK", CountryName = "Denmark", CurrencyId = 57 });
            this.Insert.IntoTable("Countries").Row(new { Code = "DOM", CountryName = "Dominican Republic", CurrencyId = 59 });
            this.Insert.IntoTable("Countries").Row(new { Code = "DZA", CountryName = "Algeria", CurrencyId = 60 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ECU", CountryName = "Ecuador", CurrencyId = 61 });
            this.Insert.IntoTable("Countries").Row(new { Code = "EGY", CountryName = "Egypt", CurrencyId = 63 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ERI", CountryName = "Eritrea", CurrencyId = 65 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ESH", CountryName = "Western Sahara", CurrencyId = 64 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ESP", CountryName = "Spain", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "EST", CountryName = "Estonia", CurrencyId = 62 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ETH", CountryName = "Ethiopia", CurrencyId = 65 });
            this.Insert.IntoTable("Countries").Row(new { Code = "FIN", CountryName = "Finland", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "FJI", CountryName = "Fiji", CurrencyId = 69 });
            this.Insert.IntoTable("Countries").Row(new { Code = "FLK", CountryName = "Falkland Islands (Malvinas)", CurrencyId = 70 });
            this.Insert.IntoTable("Countries").Row(new { Code = "FRA", CountryName = "France", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "FRO", CountryName = "Faroe Islands", CurrencyId = 57 });
            this.Insert.IntoTable("Countries").Row(new { Code = "FSM", CountryName = "Micronesia (Federated States of)", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GAB", CountryName = "Gabon", CurrencyId = 40 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GBR", CountryName = "United Kingdom of Great Britain and Northern Ireland", CurrencyId = 75 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GEO", CountryName = "Georgia", CurrencyId = 77 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GGY", CountryName = "Guernsey", CurrencyId = 79 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GHA", CountryName = "Ghana", CurrencyId = 80 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GIB", CountryName = "Gibraltar", CurrencyId = 81 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GIN", CountryName = "Guinea", CurrencyId = 84 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GLP", CountryName = "Guadeloupe", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GMB", CountryName = "Gambia", CurrencyId = 83 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GNB", CountryName = "Guinea-Bissau", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GNQ", CountryName = "Equatorial Guinea", CurrencyId = 40 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GRC", CountryName = "Greece", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GRD", CountryName = "Grenada", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GRL", CountryName = "Greenland", CurrencyId = 57 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GTM", CountryName = "Guatemala", CurrencyId = 89 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GUF", CountryName = "French Guiana", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GUM", CountryName = "Guam", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "GUY", CountryName = "Guyana", CurrencyId = 92 });
            this.Insert.IntoTable("Countries").Row(new { Code = "HKG", CountryName = "Hong Kong", CurrencyId = 93 });
            this.Insert.IntoTable("Countries").Row(new { Code = "HMD", CountryName = "Heard Island and McDonald Islands", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "HND", CountryName = "Honduras", CurrencyId = 95 });
            this.Insert.IntoTable("Countries").Row(new { Code = "HRV", CountryName = "Croatia", CurrencyId = 96 });
            this.Insert.IntoTable("Countries").Row(new { Code = "HTI", CountryName = "Haiti", CurrencyId = 97 });
            this.Insert.IntoTable("Countries").Row(new { Code = "HUN", CountryName = "Hungary", CurrencyId = 98 });
            this.Insert.IntoTable("Countries").Row(new { Code = "IDN", CountryName = "Indonesia", CurrencyId = 99 });
            this.Insert.IntoTable("Countries").Row(new { Code = "IMN", CountryName = "Isle of Man", CurrencyId = 75 });
            this.Insert.IntoTable("Countries").Row(new { Code = "IND", CountryName = "India", CurrencyId = 32 });
            this.Insert.IntoTable("Countries").Row(new { Code = "IOT", CountryName = "British Indian Ocean Territory", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "IRL", CountryName = "Ireland", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "IRN", CountryName = "Iran (Islamic Republic of)", CurrencyId = 106 });
            this.Insert.IntoTable("Countries").Row(new { Code = "IRQ", CountryName = "Iraq", CurrencyId = 105 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ISL", CountryName = "Iceland", CurrencyId = 107 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ISR", CountryName = "Israel", CurrencyId = 101 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ITA", CountryName = "Italy", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "JAM", CountryName = "Jamaica", CurrencyId = 110 });
            this.Insert.IntoTable("Countries").Row(new { Code = "JEY", CountryName = "Jersey", CurrencyId = 75 });
            this.Insert.IntoTable("Countries").Row(new { Code = "JOR", CountryName = "Jordan", CurrencyId = 111 });
            this.Insert.IntoTable("Countries").Row(new { Code = "JPN", CountryName = "Japan", CurrencyId = 112 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KAZ", CountryName = "Kazakhstan", CurrencyId = 123 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KEN", CountryName = "Kenya", CurrencyId = 113 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KGZ", CountryName = "Kyrgyzstan", CurrencyId = 114 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KHM", CountryName = "Cambodia", CurrencyId = 115 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KIR", CountryName = "Kiribati", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KNA", CountryName = "Saint Kitts and Nevis", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KOR", CountryName = "Korea, Republic of", CurrencyId = 120 });
            this.Insert.IntoTable("Countries").Row(new { Code = "KWT", CountryName = "Kuwait", CurrencyId = 121 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LAO", CountryName = "Lao People's Democratic Republic", CurrencyId = 124 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LBN", CountryName = "Lebanon", CurrencyId = 125 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LBR", CountryName = "Liberia", CurrencyId = 129 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LBY", CountryName = "Libya", CurrencyId = 134 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LCA", CountryName = "Saint Lucia", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LIE", CountryName = "Liechtenstein", CurrencyId = 42 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LKA", CountryName = "Sri Lanka", CurrencyId = 128 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LSO", CountryName = "Lesotho", CurrencyId = 130 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LTU", CountryName = "Lithuania", CurrencyId = 131 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LUX", CountryName = "Luxembourg", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "LVA", CountryName = "Latvia", CurrencyId = 133 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MAC", CountryName = "Macao", CurrencyId = 146 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MAF", CountryName = "Saint Martin (French part)", CurrencyId = 14 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MAR", CountryName = "Morocco", CurrencyId = 64 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MCO", CountryName = "Monaco", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MDA", CountryName = "Moldova, Republic of", CurrencyId = 137 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MDG", CountryName = "Madagascar", CurrencyId = 140 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MDV", CountryName = "Maldives", CurrencyId = 153 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MEX", CountryName = "Mexico", CurrencyId = 155 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MHL", CountryName = "Marshall Islands", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MKD", CountryName = "North Macedonia", CurrencyId = 142 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MLI", CountryName = "Mali", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MLT", CountryName = "Malta", CurrencyId = 151 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MMR", CountryName = "Myanmar", CurrencyId = 144 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MNE", CountryName = "Montenegro", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MNG", CountryName = "Mongolia", CurrencyId = 145 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MNP", CountryName = "Northern Mariana Islands", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MOZ", CountryName = "Mozambique", CurrencyId = 157 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MRT", CountryName = "Mauritania", CurrencyId = 149 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MSR", CountryName = "Montserrat", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MTQ", CountryName = "Martinique", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MUS", CountryName = "Mauritius", CurrencyId = 152 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MWI", CountryName = "Malawi", CurrencyId = 154 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MYS", CountryName = "Malaysia", CurrencyId = 156 });
            this.Insert.IntoTable("Countries").Row(new { Code = "MYT", CountryName = "Mayotte", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NAM", CountryName = "Namibia", CurrencyId = 158 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NCL", CountryName = "New Caledonia", CurrencyId = 159 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NER", CountryName = "Niger", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NFK", CountryName = "Norfolk Island", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NGA", CountryName = "Nigeria", CurrencyId = 162 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NIC", CountryName = "Nicaragua", CurrencyId = 163 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NIU", CountryName = "Niue", CurrencyId = 44 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NLD", CountryName = "Netherlands", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NOR", CountryName = "Norway", CurrencyId = 33 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NPL", CountryName = "Nepal", CurrencyId = 166 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NRU", CountryName = "Nauru", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "NZL", CountryName = "New Zealand", CurrencyId = 44 });
            this.Insert.IntoTable("Countries").Row(new { Code = "OMN", CountryName = "Oman", CurrencyId = 170 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PAK", CountryName = "Pakistan", CurrencyId = 176 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PAN", CountryName = "Panama", CurrencyId = 171 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PCN", CountryName = "Pitcairn", CurrencyId = 44 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PER", CountryName = "Peru", CurrencyId = 172 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PHL", CountryName = "Philippines", CurrencyId = 175 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PLW", CountryName = "Palau", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PNG", CountryName = "Papua New Guinea", CurrencyId = 174 });
            this.Insert.IntoTable("Countries").Row(new { Code = "POL", CountryName = "Poland", CurrencyId = 177 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PRI", CountryName = "Puerto Rico", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PRK", CountryName = "Korea (Democratic People's Republic of)", CurrencyId = 119 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PRT", CountryName = "Portugal", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PRY", CountryName = "Paraguay", CurrencyId = 184 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PSE", CountryName = "Palestine, State of", CurrencyId = 111 });
            this.Insert.IntoTable("Countries").Row(new { Code = "PYF", CountryName = "French Polynesia", CurrencyId = 159 });
            this.Insert.IntoTable("Countries").Row(new { Code = "QAT", CountryName = "Qatar", CurrencyId = 185 });
            this.Insert.IntoTable("Countries").Row(new { Code = "REU", CountryName = "Réunion", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ROU", CountryName = "Romania", CurrencyId = 187 });
            this.Insert.IntoTable("Countries").Row(new { Code = "RUS", CountryName = "Russian Federation", CurrencyId = 189 });
            this.Insert.IntoTable("Countries").Row(new { Code = "RWA", CountryName = "Rwanda", CurrencyId = 190 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SAU", CountryName = "Saudi Arabia", CurrencyId = 191 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SDN", CountryName = "Sudan", CurrencyId = 194 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SEN", CountryName = "Senegal", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SGP", CountryName = "Singapore", CurrencyId = 196 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SGS", CountryName = "South Georgia and the South Sandwich Islands", CurrencyId = 75 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SHN", CountryName = "Saint Helena, Ascension and Tristan da Cunha", CurrencyId = 75 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SJM", CountryName = "Svalbard and Jan Mayen", CurrencyId = 33 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SLB", CountryName = "Solomon Islands", CurrencyId = 192 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SLE", CountryName = "Sierra Leone", CurrencyId = 201 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SLV", CountryName = "El Salvador", CurrencyId = 207 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SMR", CountryName = "San Marino", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SOM", CountryName = "Somalia", CurrencyId = 204 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SPM", CountryName = "Saint Pierre and Miquelon", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SRB", CountryName = "Serbia", CurrencyId = 188 });
            this.Insert.IntoTable("Countries").Row(new { Code = "STP", CountryName = "Sao Tome and Principe", CurrencyId = 206 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SUR", CountryName = "Suriname", CurrencyId = 205 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SVK", CountryName = "Slovakia", CurrencyId = 200 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SVN", CountryName = "Slovenia", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SWE", CountryName = "Sweden", CurrencyId = 195 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SWZ", CountryName = "Eswatini", CurrencyId = 209 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SYC", CountryName = "Seychelles", CurrencyId = 193 });
            this.Insert.IntoTable("Countries").Row(new { Code = "SYR", CountryName = "Syrian Arab Republic", CurrencyId = 208 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TCA", CountryName = "Turks and Caicos Islands", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TCD", CountryName = "Chad", CurrencyId = 40 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TGO", CountryName = "Togo", CurrencyId = 21 });
            this.Insert.IntoTable("Countries").Row(new { Code = "THA", CountryName = "Thailand", CurrencyId = 214 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TJK", CountryName = "Tajikistan", CurrencyId = 215 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TKL", CountryName = "Tokelau", CurrencyId = 44 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TKM", CountryName = "Turkmenistan", CurrencyId = 217 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TON", CountryName = "Tonga", CurrencyId = 219 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TTO", CountryName = "Trinidad and Tobago", CurrencyId = 221 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TUN", CountryName = "Tunisia", CurrencyId = 218 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TUR", CountryName = "Turkey", CurrencyId = 220 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TUV", CountryName = "Tuvalu", CurrencyId = 13 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TWN", CountryName = "Taiwan, Province of China", CurrencyId = 223 });
            this.Insert.IntoTable("Countries").Row(new { Code = "TZA", CountryName = "Tanzania, United Republic of", CurrencyId = 224 });
            this.Insert.IntoTable("Countries").Row(new { Code = "UGA", CountryName = "Uganda", CurrencyId = 226 });
            this.Insert.IntoTable("Countries").Row(new { Code = "UKR", CountryName = "Ukraine", CurrencyId = 225 });
            this.Insert.IntoTable("Countries").Row(new { Code = "UMI", CountryName = "United States Minor Outlying Islands", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "URY", CountryName = "Uruguay", CurrencyId = 229 });
            this.Insert.IntoTable("Countries").Row(new { Code = "USA", CountryName = "United States of America", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "UZB", CountryName = "Uzbekistan", CurrencyId = 230 });
            this.Insert.IntoTable("Countries").Row(new { Code = "VAT", CountryName = "Holy See", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "VCT", CountryName = "Saint Vincent and the Grenadines", CurrencyId = 4 });
            this.Insert.IntoTable("Countries").Row(new { Code = "VEN", CountryName = "Venezuela (Bolivarian Republic of)", CurrencyId = 233 });
            this.Insert.IntoTable("Countries").Row(new { Code = "VGB", CountryName = "Virgin Islands (British)", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "VIR", CountryName = "Virgin Islands (U.S.)", CurrencyId = 71 });
            this.Insert.IntoTable("Countries").Row(new { Code = "VNM", CountryName = "Viet Nam", CurrencyId = 236 });
            this.Insert.IntoTable("Countries").Row(new { Code = "VUT", CountryName = "Vanuatu", CurrencyId = 237 });
            this.Insert.IntoTable("Countries").Row(new { Code = "WLF", CountryName = "Wallis and Futuna", CurrencyId = 159 });
            this.Insert.IntoTable("Countries").Row(new { Code = "WSM", CountryName = "Samoa", CurrencyId = 1 });
            this.Insert.IntoTable("Countries").Row(new { Code = "YEM", CountryName = "Yemen", CurrencyId = 240 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ZAF", CountryName = "South Africa", CurrencyId = 242 });
            this.Insert.IntoTable("Countries").Row(new { Code = "ZMB", CountryName = "Zambia", CurrencyId = 243 });




        }
    }
}