using Serenity.Navigation;
using MyPages = BitPro.SchoolMate.Master.Pages;
[assembly: NavigationMenu(int.MaxValue, "Master", icon: "fa fa-cube")]
[assembly: NavigationLink(int.MaxValue, "Master/Areas", typeof(MyPages.AreasController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Campuses", typeof(MyPages.CampusesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Academic Year", typeof(MyPages.AcadamicYearController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Currencies", typeof(MyPages.CurrenciesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Countries", typeof(MyPages.CountriesController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Subjects", typeof(MyPages.SubjectsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Contacts", typeof(MyPages.ContactsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Staffs", typeof(MyPages.StaffsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Staff Subjects", typeof(MyPages.StaffSubjectsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Courses", typeof(MyPages.CoursesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Course Subjects", typeof(MyPages.CourseSubjectsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Fees", typeof(MyPages.FeesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Course Fee", typeof(MyPages.CourseFeeController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Fee Terms", typeof(MyPages.FeeTermsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Fee Structure", typeof(MyPages.FeeStructureController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Students", typeof(MyPages.StudentsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Fee Excemptions", typeof(MyPages.FeeExcemptionsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Divisions", typeof(MyPages.DivisionsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Division Students", typeof(MyPages.DivisionStudentsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Account Heads", typeof(MyPages.AccountHeadsController), icon: null)]
[assembly: NavigationLink(int.MaxValue, "Master/Exams", typeof(MyPages.ExamsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Student Current Courses", typeof(MyPages.StudentCurrentCoursesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Course Divisions", typeof(MyPages.CourseDivisionsController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Exam Courses", typeof(MyPages.ExamCoursesController), icon: null)]
//[assembly: NavigationLink(int.MaxValue, "Master/Exam Max Marks", typeof(MyPages.ExamMaxMarksController), icon: null)]